service: serverless-toll
plugins:
  # - serverless-dotenv-plugin
  - serverless-dynamodb-local
  - serverless-offline

# custom:
#   dynamodb:
#     start:
#       port: 8000
#       inMemory: true
#       migrate: true
#     migration:
#       dir: offline/migrations
# app: seattle-toll
# org: ronbarrantes

provider:
  name: aws
  runtime: nodejs12.x

  stage: dev
  region: us-west-2

  environment:
    # DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}
    TOLL_URI: https://www.wsdot.wa.gov
    TOLL_99: tolling/sr-99-tunnel-toll-rates
    TOLL_520: Tolling/520/520tollrates.htm

package:
  exclude:
    - index.js
    - temp/**

functions:
  getTolls:
    handler: src/functions/handler.getTolls
    events:
      - http:
          path: /api/v1/tolls/getTolls
          method: get

  # create:
  #   handler: src/functions/handler.create
  #   events:
  #     - http:
  #         path: /api/v1/tolls
  #         method: post  

  list:
    handler: src/functions/handler.list
    events:
      - http:
          path: /api/v1/tolls
          method: get  

  # delete:

# resources:
#   Resources:
#     TollsDynamoTable:
#       Type: 'AWS::DynamoDB::Table'
#       Properties:
#         AttributeDefinitions:
#           - AttributeName: id
#             AttributeType: S
#         KeySchema:
#           - AttributeName: id
#             KeyType: HASH
#         BillingMode: PAY_PER_REQUEST
#         TableName: ${self:provider.environment.DYNAMODB_TABLE}
