service: serverless-toll
plugins:
  - serverless-dotenv-plugin
  - serverless-dynamodb-local
  - serverless-offline

custom:
  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true
    migration:
      dir: offline/migrations
        

app: seattle-toll
org: ronbarrantes

provider:
  name: aws
  runtime: nodejs12.x

  stage: dev
  region: us-west-2

environment:
  TOLL_URI: ${env:TOLL_URI}
  TOLL_99: ${env:TOLL_99}
  TOLL_520: ${env:TOLL_520}
  DYNAMODB_TABLE: ${self:service}-db #${opt:stage, self:provider.stage}

package:
  exclude:
    - index.js
    - temp/**

functions:
  getTolls:
    handler: src/functions/handler.getTolls
    events:
      - http:
          path: /api/v1/tolls/getTolls
          method: get

  create:
    handler: src/functions/handler.create
    events:
      - http:
          path: /api/v1/tolls
          method: post  
  # create:
  # handler: src/functions/handler.create
  # events:
  #   - http:
  #       path: /api/v1/tolls
  #       method: get
  

  # list:
  #   handler: src/function/handler.list
  #   events:
  #     - http:
  #         path: /api/v1/tolls
  #         method: get

  # delete:




# resources:
#   Resources:
#     TollsDynamoTable:
#       Type: 'AWS::DynamoDB::Table'
#       Properties:
#         AttributeDefinitions:
#           - AttributeName: id
#             AttributeType: S
#         KeySchema:
#           - AttributeName: id
#             KeyType: HASH
#         BillingMode: PAY_PER_REQUEST
#         TableName: ${self:provider.environment.DYNAMODB_TABLE}
